baseURL = "https://danysk.github.io/course-laboratory-of-software-systems"
languageCode = "en-us"
title = "Laboratory of Software Systems"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"
publishDir = "build"
ignoreFiles = ['.*generator.md$']

# relativeURLs = "true"
# uglyURLs = "true"

[author]
name = "Danilo Pianini"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
theme = "white"
#width = '100%'
#height = '100%'
# embedded = 'true'
# disableLayout = 'true'
pdfSeparateFragments = false
slide_number = true
transition = "slide"
transition_speed = "fast"
custom_theme = "custom-theme.scss"
custom_theme_compile = true
width = '1440'
height = '900'

[reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
#style = "monokailight"
style = "pastie"
#style = "pygments"

[[params.reveal_hugo.mermaid]]
startOnLoad = false
theme = "default"
fontFamily = "Inconsolata"
useMaxWidth = false

[params.reveal_hugo.mermaid.gitGraph]
mainBranchName = 'master'
rotateCommitLabel = true
