name: Check Gradle projects
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'slides/**'
      - '.github/workflows/build-and-deploy.yml'
      - '.github/workflows/update-hugo.yml'
  pull_request:
  workflow_dispatch:

jobs:
  check-projects:
    strategy:
      matrix:
        os: [ windows-2022, macos-12, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-check-${{ matrix.os }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    env:
      TERM: dumb
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.10
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 16
      - name: Configure the Windows Pagefile
        if: ${{ runner.os == 'Windows' }}
        uses: al-cheb/configure-pagefile-action@v1.3
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-:
      - working-directory: code/automation
        shell: bash
        run: ./integrity_check.sh
      - name: Stop all gradle daemons
        working-directory: code/automation
        shell: bash
        run: |
          gradle --stop
          for directory in *; do
            if [[ -d "$directory" ]]; then
                cd "$directory"
                if [[ -x gradlew ]]; then
                    ./gradlew --stop
                fi
            fi
          done
  success:
    runs-on: ubuntu-22.04
    needs:
      - check-projects
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
